Devarshi feature 2
gcivil-nyu-org/Wednesday-Fall2023-Team-4 pull request #119
Opened 2023-11-04 00:14 UTC by dc5212

2023-11-04 23:39 UTC, himanshu1196 requested changes

2023-11-05 00:41 UTC, dc5212 commented on rrapp/views.py
> +            filters &= Q(number_of_bedrooms__lte=number_of_bedrooms)
Using LTE to display the bedrooms or rent or bathrooms upto that value the user wants which I think can be more useful for a user to choose instead of showing the results with exact value

2023-11-05 00:41 UTC, dc5212 commented on rrapp/views.py
> +        number_of_bathrooms = self.request.GET.get('number_of_bathrooms')
Using LTE to display the bedrooms or rent or bathrooms upto that value the user wants which I think can be more useful for a user to choose instead of showing the results with exact value

2023-11-05 00:46 UTC, dc5212 commented on rrapp/views.py
> +            filters &= Q(food_groups_allowed=food_groups_allowed)
So if you mean if I have selected Vegan in the dropdown the listings that have ALL should also be displayed along with Vegan?

2023-11-05 00:46 UTC, dc5212 commented on rrapp/views.py
> +    @method_decorator(login_required, name='dispatch')
This was a redundant code...My bad removed it

2023-11-05 02:16 UTC, dc5212 commented on rrapp/views.py
> +        all_listings = all_listings.order_by(sort_option)
Done

2023-11-05 02:17 UTC, dc5212 commented on rrapp/views.py
> +        if sort_option not in ['created_at', 'monthly_rent', 'number_of_bedrooms',
Done

2023-11-06 17:55 UTC, dc5212 commented on rrapp/views.py
> +            filters &= Q(number_of_bedrooms__lte=number_of_bedrooms)
Will change later

2023-11-06 17:55 UTC, dc5212 commented on rrapp/views.py
> +            filters &= Q(food_groups_allowed=food_groups_allowed)
Will change later

2023-11-06 17:55 UTC, dc5212 commented on rrapp/views.py
> +        number_of_bathrooms = self.request.GET.get('number_of_bathrooms')
Will change later

2023-11-06 19:20 UTC, himanshu1196 commented on .travis.yml
> +  - black ./ --skip-string-normalization --exclude settings* --extend-exclude migrations* --extend-exclude venv* -v
This is incorrect. black should only check during the build, not refactor the files

2023-11-06 19:22 UTC, dc5212 commented on .travis.yml
> +  - black ./ --skip-string-normalization --exclude settings* --extend-exclude migrations* --extend-exclude venv* -v
Done

2023-11-06 20:14 UTC, himanshu1196 approved these changes
Reviewed with planned remaining changes

2023-11-06 20:38 UTC, merged